// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0C9vZXtEU_wrBGTyK6sHaEl-iIFehbcs',
    appId: '1:350927266597:web:c7a60997bd0c56148730cc',
    messagingSenderId: '350927266597',
    projectId: 'udemy-firebase-c83d3',
    authDomain: 'udemy-firebase-c83d3.firebaseapp.com',
    storageBucket: 'udemy-firebase-c83d3.appspot.com',
    measurementId: 'G-NWBGSC4BWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-lviLOEbiT-ZuYZIAKh99m_Z9kyi4T6U',
    appId: '1:350927266597:android:72ec518e1b40316f8730cc',
    messagingSenderId: '350927266597',
    projectId: 'udemy-firebase-c83d3',
    storageBucket: 'udemy-firebase-c83d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJM1NiMjatEMIHgKBEiEKw3fQGwDe0ov4',
    appId: '1:350927266597:ios:2ee92819d6ded6f58730cc',
    messagingSenderId: '350927266597',
    projectId: 'udemy-firebase-c83d3',
    storageBucket: 'udemy-firebase-c83d3.appspot.com',
    iosClientId: '350927266597-qodraihe8u5qcijitj11gs81305166n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemyfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJM1NiMjatEMIHgKBEiEKw3fQGwDe0ov4',
    appId: '1:350927266597:ios:2ee92819d6ded6f58730cc',
    messagingSenderId: '350927266597',
    projectId: 'udemy-firebase-c83d3',
    storageBucket: 'udemy-firebase-c83d3.appspot.com',
    iosClientId: '350927266597-qodraihe8u5qcijitj11gs81305166n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemyfirebase',
  );
}
